server:
  port: 8082
  http2:
    enabled: true

spring:
  application:
    name: CustomerService
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
  web:
    resources:
      add-mappings: true
  threads:
    virtual:
      enabled: true
