services:
  products-db:
    image: postgres:16.3
    container_name: products-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5430:5432
    command: ["postgres", "-c", "log_statement=all"]

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 9090:8080

volumes:
  pgdata: