spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    url: jdbc:postgresql://localhost:5430/products
    username: user
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  web:
    resources:
      add-mappings: true

logging:
  level:
    root: INFO
    at.kocmana.testservice: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: TRACE

service:
  delay:
    enable-endpoint-delays: true
    enable-service-delays: true
    service-delay-mean: 150
    service-delay-standard-deviation: 50
    log-delays: true
