server:
  port: 8080

spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      add-mappings: true
  sql:
    init:
      data-locations: classpath*:sql/testdata.sql
      schema-locations: classpath*:sql/schema.sql

logging:
  level:
    root: INFO
    at.kocmana.testservice: INFO
    org.hibernate.SQL: WARN

security:
  whitelist:
    - /h2-console/**

service:
  delay:
    enable-endpoint-delays: true
    enable-service-delays: true
    service-delay-mean: 500
    service-delay-standard-deviation: 500
    log-delays: true

customerservice:
  api-key:
    header: x-api-key
    values:
      - supersecret
      - megasecret
      - toptoptopsecret
